---

- name: Copy {{ pwm_HTTP_server }} configuration
  template:
    src: pwm.conf-{{ jellyfin_HTTP_server }}.j2
    dest: "{{ pwm_site_config }}"
  when: not pwm_HTTP_configured

- name: Enable pwm site
  file:
    src: /etc/{{ pwm_HTTP_server }}/sites-available/pwm.conf
    dest: /etc/{{ pwm_HTTP_server }}/sites-enabled/pwm.conf
    state: link
  when: not pwm_HTTP_configured

# find a location block and add a new location for pwm after that location block
- name: add site location /pwm to {{ pwm_HTTP_server }}
  blockinfile:
    path: "{{ pwm_site_config }}"
    backup: yes
    insertafter: "listen 443 ssl http2;"
    block: |
      location /pwm {
               # Proxy pwm traffic
               proxy_pass http://127.0.0.1:8080/pwm;
               proxy_set_header Host $host;
               proxy_set_header X-Real-IP $remote_addr;
               proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
               proxy_set_header X-Forwarded-Proto $scheme;
               proxy_set_header X-Forwarded-Protocol $scheme;
               proxy_set_header X-Forwarded-Host $http_host;
      }
    state: present
  when: pwm_HTTP_configured

- name: Restart web server - {{ pwm_HTTP_server }}
  systemd:
    name: "{{ pwm_HTTP_server }}"
    state: restarted

...