---
# from: https://docs.google.com/document/d/1DtiDX2fbNco-f1fQKIVDsanOxX7WLS08mHOs10kKMow/edit

- name: Template LDIF - pwmUser schema
  template:
    src: templates/pwm_openldap.schema.j2
    dest: /tmp/ldap.ldif
  when: pwm_ldap_type == "OPEN_LDAP"

- name: Add the pwmUser schema
  command: ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/ldap.ldif
  register: command_result
  failed_when:
    - command_result.rc > 0
    - '"Type or value exists" not in command_result.stderr'
    - '"Duplicate attributeType" not in command_result.stderr'
  when: pwm_ldap_type == "OPEN_LDAP"

- name: Clean LDIF
  file:
    state: absent
    path: /tmp/ldap.ldif
  when: pwm_ldap_type == "OPEN_LDAP"

- name: Template LDIF - ACL
  template:
    src: templates/pwm_openldap.acl.j2
    dest: /tmp/ldap.ldif
  when: pwm_ldap_type == "OPEN_LDAP"

- name: Apply ACL needed for PWM
  command: ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/ldap.ldif
  register: command_result
  failed_when:
    - command_result.rc > 0
    - '"Type or value exists" not in command_result.stderr'
  when: pwm_ldap_type == "OPEN_LDAP"

- name: Clean LDIF
  file:
    state: absent
    path: /tmp/ldap.ldif
  when: pwm_ldap_type == "OPEN_LDAP"

- name: Add pwmUser object class to the ldap test user
  ldap_entry:
    dn: "{{ pwm_ldap_test_user }}"
    state: present
    objectClass:
      - pwmUser
      - inetOrgPerson
    attributes:
      sn: "{{ pwm_ldap_test_user_sn }}"
      cn: "{{ pwm_ldap_test_user_sn }}"
      description: account used by pwm to test password management operations
  when: pwm_ldap_type == "OPEN_LDAP"

...